### ISSUE TITLE
Another alpha release?

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-next-gen#103]
Some classes at ITP/IMA are going to be using ml5.js in the next couple weeks. Shall we do another alpha release and update the [temporary docs](https://github.com/ml5js/ml5-next-gen/blob/main/documentation.md) and [web editor collection](https://editor.p5js.org/ml5/collections/pUzWMkdmE)?  @ziyuan-linn we can do the release together like last time?

@MOQN and team, what's your best guess as to the website timeline?

**Comment by ziyuan-linn** [comment]
I am happy to find a time together and do another release! I will try to update the temporary docs in the meantime. Are there any updates about the p5 web editor API? If not, I can also manually update the web editor collection.

**Comment by jackbdu** [comment]
Hello, I'm working on a series of [ml5.js tutorials](https://github.com/ml5js/ml5-website-v02-gatsby/issues/2) and would very much appreciate another alpha release soon-ish, especially considering the model names' camelCase change. Thank you all for working on this!

**Comment by shiffman** [comment]
> I am happy to find a time together and do another release! I will try to update the temporary docs in the meantime. Are there any updates about the p5 web editor API? If not, I can also manually update the web editor collection.

Unfortunately I think we need to do the p5 web editor examples manually still, let's circle back to our email thread about this!

@ziyuan-linn I was thinking maybe it might be interesting for the ml5 studio class to see the process of posting a release? Do you happen to be free on Wednesday morning?

**Comment by ziyuan-linn** [comment]
> Unfortunately I think we need to do the p5 web editor examples manually still, let's circle back to our email thread about this!

Sounds good, I can update them manually for now.

> I was thinking maybe it might be interesting for the ml5 studio class to see the process of posting a release? Do you happen to be free on Wednesday morning?

@shiffman I unfortunately have another class during the ml5 studio class, but feel free to do the release without me and let me know how it goes!

**Comment by ziyuan-linn** [comment]
We have released `0.20.0-alpha.4`!
