### ISSUE TITLE
`faceMesh` lips missing `keypoint` 291

### ISSUE THREAD

**Issue by jackbdu** [ml5js/ml5-next-gen#107]
Hi all, I noticed in the [faceMesh parts example](https://editor.p5js.org/ml5/sketches/9y9W7eAee), there is a missing keypoint (291 on the [mesh_map](https://github.com/tensorflow/tfjs-models/blob/master/face-landmarks-detection/mesh_map.jpg)). See [this sketch with keypoint 291 drawn in red](https://editor.p5js.org/jackbdu/sketches/Js50jtdVg). The same issue is present in [the original tfjs demo](https://storage.googleapis.com/tfjs-models/demos/face-landmarks-detection/index.html?model=mediapipe_face_mesh) so I'm not sure what we should do. Would it make sense to manually add this keypoint in ml5 for the time being (until it's fixed in tfjs)?

**Comment by ziyuan-linn** [comment]
@jackbdu thank you for submitting this issue! We certainly should open an issue with tfjs about this. In the meantime, it should be simple to fix this within ml5 temporarily.

**Comment by shiffman** [comment]
Thank you @jackbdu for reporting and @ziyuan-linn for adding support! How does this affect the documentation? cc @B2xx who is working on this. Does anyone want to volunteer to open the tf.js issue?

**Comment by jackbdu** [comment]
@ziyuan-linn Thank you for addressing this so quickly!

I went ahead and [opened an issue about this on tfjs repo](https://github.com/tensorflow/tfjs/issues/8221).
