### ISSUE TITLE
`confidence` vs `score` across all models

### ISSUE THREAD

**Issue by ziyuan-linn** [ml5js/ml5-next-gen#124]
Just keeping a note that we should be consistent about using `confidence` vs `score` across all models.

It seems like in [a previous discussion](https://github.com/ml5js/ml5-next-gen/pull/39#discussion_r1313201835) we were leaning toward using `confidence`. Just wondering if anyone have any additional thoughts about it.

**Comment by MOQN** [comment]
I vote for “confidence” too!

**Comment by shiffman** [comment]
Let's go with confidence!
