### ISSUE TITLE
Google search for reference leads to a non existing page

### ISSUE THREAD

**Issue by GuilhermeMDurao** [ml5js/ml5-next-gen#160]
<img width="1032" alt="image" src="https://github.com/ml5js/ml5-next-gen/assets/17754148/6330439f-bb58-4cf2-b75d-b9f0202779dc">

**Comment by GuilhermeMDurao** [comment]
<img width="788" alt="image" src="https://github.com/ml5js/ml5-next-gen/assets/17754148/a5b417c9-d297-4ef6-a83d-5835742848ff">

**Comment by ziyuan-linn** [comment]
Hi @GuilhermeMDurao, thank you for submitting this issue! With the release of the version 1.0 library, we changed the address of the reference page. learn.ml5js.org is no longer used.

- The URL to the new reference page (for version 1.0 and above): https://docs.ml5js.org/
- The URL to the archived reference page for now (for version 0.12.2 and below): https://archive-docs.ml5js.org/

Hopefully Google has re-indexed by now and the nonexisting page is no longer showing up in search.

**Comment by ziyuan-linn** [comment]
Closing this issue since Google is now correctly indexing the pages!
