### ISSUE TITLE
featureExtractor() not working

### ISSUE THREAD

**Issue by SoorajprasadZD** [ml5js/ml5-next-gen#162]
mobileNet = ml5.featureExtractor("MobileNet", () => {
    console.log("model ready");
  });
  
  
  Uncaught (in promise) TypeError: ml5.featureExtractor is not a function
    at preload (sketch.js:68:19)
    at _._start (p5.min.js:3:294800)
    at new _ (p5.min.js:3:298631)
    at p5.min.js:3:290388

**Comment by ziyuan-linn** [comment]
Hi @SoorajprasadZD, thank you for submitting this issue! `ml5.featureExtractor` has not been implemented in the newly released `1.0.1` version of the library. We hope to bring it back soon in a future release.

If you would like to use `ml5.featureExtractor`, try version `0.12.2` of the library. In the HTML file, change the version number of ml5 from `1.0.1` or `latest` to `0.12.2`. You should end up with something like:
```html
<script src="https://unpkg.com/ml5@0.12.2/dist/ml5.min.js"></script>
```
This should bring back `featureExtractor`!
