### ISSUE TITLE
Question: choice behind paring down of the `callback(error, results)` syntax from v0 to `callback(results)`?

### ISSUE THREAD

**Issue by jchwenger** [ml5js/ml5-next-gen#198]
Hi lovely ml5 people!

Very glad to see the new release! I'm in the process of updating a series of examples and a question springs to mind (not a bug, really): previously, many examples using callbacks to handle predictions would follow the following syntax:

```javascript
 classifier.classify(img, gotResult);

// callback
function gotResult(error, results) {
  // Display error in the console
  if (error) {
    console.error(error);
  }
  // Do something with results
}
```

This has now been reduced to only `gotResult(results)`, I wondered why, and what would be your recommendation for error handling in the new framework (perhaps you included that within the model methods directly)?

I'm unsure, to be honest, if that's an ml5 question proper, or more like a JS pattern one, so apologies if this question isn't in the right place!

**Comment by jchwenger** [comment]
Hi @ziyuan-linn,

Thanks for the quick reply, that makes complete sense! I also fully approve the choice, I also think it's more intuitive this way 🙌 !

I have been using ml5 for projects and teaching and I am eager to see the new version evolve. Is it better here, for question, or on the discord? Thanks!

**Comment by ziyuan-linn** [comment]
Here or discord works! Feel free to use the one you prefer.
