### ISSUE TITLE
i need moveNet  in ML5

### ISSUE THREAD

**Issue by zjtxxjd** [ml5js/ml5-next-gen#20]
Dear ml5 community,
i need moveNet in my projects.so when is MoveNet supported in ML5?

**Comment by ziyuan-linn** [comment]
Hi @zjtxxjd, thank you for submitting this issue! I apologize for the late response.

In the current alpha release (0.20.0-alpha.3), `ml5.bodypose` uses `MoveNet` as the underlying model by default.  You can access the release via the URL below:
```
https://unpkg.com/ml5@0.20.0-alpha.3/dist/ml5.js
```

We are also planning to make another alpha release soon so please stay tuned!
