### ISSUE TITLE
`normalizeData()` does not handle only zeros in one of the inputs to the neural net

### ISSUE THREAD

**Issue by jchwenger** [ml5js/ml5-next-gen#204]
Hi there,

I've been noticing what seems to be a little bug.

If you go to [this example](https://editor.p5js.org/ml5/sketches/eGHBdmCLe) and comment out all examples for one class, e.g. all the "blue-ish" objects, training fails with infinite loss, because the normalized data has `NaN`s in the third coordinate of xs (check `classifier.data`). I bumped into this in [this sketch](https://editor.p5js.org/jchwenger/sketches/71cFcKwS2), where again I would like this to work even if only two classes are provided. As long there's nonzero numbers everywhere in the training input, it's fine, but normalizing zeros doesn't seem to work. I wonder where you would want to add a check for this: directly in `normalizeDataRaw`?

**Comment by ziyuan-linn** [comment]
Hi @jchwenger,

Thank you again!

It seems like the code uses `(value - min) / (max - min)` to compute the normalized values. This will divide by zero if `min == max`, which is the source of the `NaN`. When all values of a parameter are the same, the bug will occur.

I opened PR #208 to address this.

From local testing, the linked sketch now works even if not all classes are provided.
<img width="300" alt="Screenshot 2024-09-23 at 6 10 07 PM" src="https://github.com/user-attachments/assets/77ec3052-5d03-4303-a223-4c9800290c05">

**Comment by jchwenger** [comment]
Hi @ziyuan-linn, awesomeness! Nice thinking, this check, looking forward to the pr being integrated!
