### ISSUE TITLE
nn.loadData() appears to be broken

### ISSUE THREAD

**Issue by gohai** [ml5js/ml5-next-gen#206]
When loading a JSON file produced by `nn.saveData()`, the following error message is returned (with the latest 1.x version of the library): `data must be a json object containing an array called "data"`

To reproduce: try pressing `l` in [this sketch](https://editor.p5js.org/gohai/sketches/LGnxcG-5C). The `data3.json` file has been produced using the same code (same ml5 version).

**Comment by ziyuan-linn** [comment]
@gohai Thank you for submitting this issue! Looks like there was an incorrect call to `JSON.stringify` on an already stringified JSON object. I opened a PR to fix this.
