### ISSUE TITLE
Broken link in `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by alanvww** [ml5js/ml5-next-gen#209]
In the table of content of [`CONTRIBUTING.md`](https://github.com/ml5js/ml5-next-gen/blob/31edf94152276617e2254734016e439cc1a8b15e/CONTRIBUTING.md), the link of **Contributing Workflow** should be https://github.com/ml5js/ml5-next-gen/blob/31edf94152276617e2254734016e439cc1a8b15e/CONTRIBUTING.md#contribution-workflow instead of `.../CONTRIBUTING.md#contributing-workflow`

<del>` - [Contributing Workflow](#contributing-workflow) `</del>
` - [Contribution Workflow](#contribution-workflow) `

@ziyuan-linn

**Comment by shiffman** [comment]
Just checked and this got resolved somewhere along the way!
