### ISSUE TITLE
BodySegmentation (BodyPix) breaks if you rename the video variable

### ISSUE THREAD

**Issue by agrshch** [ml5js/ml5-next-gen#212]
Hello everyone! 

On the BodySegmentation reference page under the [Quick Start](https://docs.ml5js.org/#/reference/body-segmentation?id=quick-start) chapter there is a code example https://editor.p5js.org/ml5/sketches/ruoyal-RC

There is a variable in this example called video, which stores a webcam feed. If you rename this variable to literally anything else (video2 for instance), the code stops working, throws the "ReferenceError: video is not defined" at constructor (webpack:https://ml5/src/BodySegmentation/index.js:34:17) 

It looks like the problem is here:

<img width="687" alt="Screenshot 2024-10-10 at 22 33 22" src="https://github.com/user-attachments/assets/774f2779-a5c1-43cc-9e07-2d484b3c7179">

The constructor does not expect any video to be passed in, so it relies on a global variable called video in the sketch

**Comment by ziyuan-linn** [comment]
Thank you @agrshch for submitting this issue and making a PR! I think there once was a `video` parameter for the constructor and we forgot to remove the `this.video` property when we removed the `video` parameter. Your fix looks great!
