### ISSUE TITLE
Getting error message in console: Initialization of backend webgpu failed

### ISSUE THREAD

**Issue by jht9629-nyu** [ml5js/ml5-next-gen#231]
### Issue Type

Runtime Error, Unexpected Behavior

### ml5.js Version

v.1.2.0 Latest

### Development Environment

p5js editror

### Browser & Operating System

Chrome Macos Version 131.0.6778.69 (Official Build) (arm64)

### Issue Description

From documentation:
https://docs.ml5js.org/#/reference/bodypose

run the example sketch:
https://editor.p5js.org/ml5/sketches/hMN9GdrO3
Following error is displayed in console:
Initialization of backend webgpu failed
index.js:259 TypeError: t.requestAdapterInfo is not a function
    at Object.factory (pose-detection.esm.js:17:97544)
    at async b.ready (engine.js:93:13)
    at async fG.loadModel (index.js:256:7)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TimChen3345** [comment]
I am running into the same issue:
https://editor.p5js.org/tc3902/sketches/7h4WyQQe7

Here is the error I got in console:

Initialization of backend webgpu failed 
TypeError: t.requestAdapterInfo is not a function
    at Object.factory (https://unpkg.com/ml5@1/dist/ml5.min.js:18352:117148)
    at async b.ready (https://unpkg.com/ml5@1/dist/ml5.min.js:102:916)
    at async fG.loadModel (https://unpkg.com/ml5@1/dist/ml5.min.js:18359:1917)

**Comment by shiffman** [comment]
I've been noticing this issue recently as well, it seems to come and go, it's very strange! I wonder if it's something related to chrome/webgpu update? It resolves if you force a non-webgpu backend, for example:

```js
ml5.setBackend('webgl');
```

**Comment by TimChen3345** [comment]
It works! Thanks!

**Comment by jht9629-nyu** [comment]
Error message does not appear to affect behavior,
my sketches still work with it.
Using ml5.setBackend("webgl") @shiffman recommends make the error message go away.

**Comment by ziyuan-linn** [comment]
@shiffman When `webgpu` backend fails, tfjs automatically rolls back to `webgl`. I tried logging the backend after the warning:
<img src="https://github.com/user-attachments/assets/61d017c9-8682-4bde-af6e-8447f58e063a" width="400px" alt="backend is logged as webgl after the warning">

The tfjs `webgpu` backend called the [`requestAdapterInfo`](https://developer.mozilla.org/en-US/docs/Web/API/GPUAdapter/requestAdapterInfo) function. This function is deprecated and non-standard, so Chrome might have removed it during a recent update.

It looks like this issue has already been addressed by tfjs in https://github.com/tensorflow/tfjs/pull/8392, which is released in [tfjs-v4.22.0](https://github.com/tensorflow/tfjs/releases/tag/tfjs-v4.22.0). I think bumping our dependency versions should fix the issue.

This might also be a good opportunity to look into bringing back [Dependabot](https://github.com/dependabot), which automatically checks for dependency updates.

**Comment by shiffman** [comment]
Thank you @ziyuan-linn! I re-enabled dependabot in the repo as well as updated tensorflow.js version in #232. I haven't had a chance to test it yet though. Take a look and we can do a quick release for just this update if need be!
