### ISSUE TITLE
1.2.1 release

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-next-gen#234]
I published 1.2.1, see: https://github.com/ml5js/ml5-next-gen/releases/tag/v1.2.1

@ziyuan-linn can you double-check that it looks correct and the #231 is resolved?

Weirdly, it's working for me if I reference:

```html
    <script src="https://unpkg.com/ml5@1.2.1/dist/ml5.min.js"></script>
```

But I am still getting the error message with:

```html
    <script src="https://unpkg.com/ml5@1/dist/ml5.min.js"></script>
```

I wonder if it's possible I missed a step or more likely there is just some kind of caching going on?

**Comment by ziyuan-linn** [comment]
@shiffman On my end `ml5@1` does not produce the warning. I think the release was successful and it is probably just a caching issue!

Does the community statement console log say `🌟 Thank you for using ml5.js v1.2.1 🌟` or `🌟 Thank you for using ml5.js v1.2.0 🌟` on your end for `<script src="https://unpkg.com/ml5@1/dist/ml5.min.js"></script>`?

**Comment by shiffman** [comment]
Yes, the warning is gone and I do see `🌟 Thank you for using ml5.js v1.2.1 🌟` with version `@1`!
