### ISSUE TITLE
body segmentation performance

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-next-gen#62]
I'm filing an issue to continue a discussion with @golanlevin on twitter ([see this thread](https://editor.p5js.org/ml5/sketches/KNsdeNhrp)). 

> It will be worth A/B testing against the MediaPipe implementations. E.g., I'm getting 30fps using their body segmentation, 
https://mediapipe-studio.webapps.google.com/studio/demo/image_segmenter
but only 5fps with ML5's new version, 
[https://editor.p5js.org/ml5/sketches/KNsdeNhrp](https://t.co/Ek6w6rhxL5)

@ziyuan-linn could #61 be related?

**Comment by ziyuan-linn** [comment]
@shiffman I think it is possibly related. I tried [a bodyPix demo here](https://storage.googleapis.com/tfjs-models/demos/body-segmentation/index.html?model=selfie_segmentation), and I am getting around 55fps vs 12fps in the p5 sketch. Unlike our implementation, the demo also does not generate requests or add images to the sources. I am not exactly sure what's happening, but I am happy to look into this further. 

We could also consider adding other segmentation models like MediaPipeSelfieSegmentation and BlazePose, which might be better performing.

**Comment by ziyuan-linn** [comment]
After looking through bodyPix's code, I think the challenge is converting the model's output, which is an `ImageData` to a `p5.image` object. 

The current library converts the `ImageData` object to a `Blob` object, generates an object URL of the blob, and then creates a p5 image by calling the `p5.loadImage()` function with the URL (which fetches the URL, hence network request). The original ml5 library is also using this pattern, and I think this is where the slow-down occurs.

There should be a more efficient way of handling this. On top of my head, we could use the `p5.Image.updatePixels()` function to load the raw `Uint8ClampedArray` pixel data into a p5 Image.
