### ISSUE TITLE
camelCase pose models?

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-next-gen#72]
I'm doing final edits of my Nature of Code book and I noticed that I had referenced `ml5.handpose()`. I initially thought this was a typo and it should be `ml5.handPose()`, but looking at the existing models and examples, I see it is `handpose()`! I don't have a strong feeling one way or another but since I'm finishing the book it might be nice to make a decision:

* `handpose` vs. `handPose`
* `bodypose` vs `bodyPose`
* `facemesh` vs. `faceMesh`

Thoughts @sproutleaf @ziyuan-linn @MOQN @gohai? I do see we have `bodySegmentation` and `imageClassifier` so perhaps the `camelCase` is more consistent?

Sorry for the tags, but my deadline is Friday lol! (I mean, it can be wrong in the book, it won't be the end of the world.)

**Comment by MOQN** [comment]
Hi Dan,

Thanks for bringing this up! Interestingly I had a similar thought last year as well.

I just did a quick search on Google with the keyword “handpose," and I found instances of both “handpose" and “handPose," along with more instances of "Hand Pose." However, if the term is commonly split into two separate words, then using camelCase makes sense to me.

It is confusing on TensorFlow’s GitHub pages as well, as they use it in a mixed way. Please take a look at the screenshots attached below. I assume the model is named “Handpose," but in some code examples (i.e. Hand Pose Detection), they seem to be following common conventions.

My preference leans slightly towards using camelCase. We could name our model according to standard conventions (?).

Best,
Moon

￼

￼

**Comment by gohai** [comment]
(I believe your images might not have made it across, @MOQN. +1 on what you wrote)

**Comment by MOQN** [comment]
Haha, I sensed it after sending them via email. Let me modify the post on GitHub!MoonSent from my iPhone.Please excuse my brevity and typos.On Feb 6, 2024, at 9:32 AM, Gottfried Haider ***@***.***> wrote:﻿
(I believe your images might not have made it across, @MOQN. +1 on what you wrote)

**Comment by MOQN** [comment]
Here are the two parts I was referring to:

<img width="1248" alt="Screenshot 2024-02-06 at 9 13 45 AM" src="https://github.com/ml5js/ml5-next-gen/assets/2150896/9bf4d3b7-6706-41e4-a40b-26634fade023">

```
async function main() {
  // Load the MediaPipe handpose model.
  const model = await handpose.load();
```

<img width="1243" alt="Screenshot 2024-02-06 at 9 14 47 AM" src="https://github.com/ml5js/ml5-next-gen/assets/2150896/07bc9ab5-b5d9-467e-bf0f-2dc9f54ba95a">


```
const model = handPoseDetection.SupportedModels.MediaPipeHands;
const detectorConfig = {
  runtime: 'mediapipe', // or 'tfjs',
  solutionPath: 'https://cdn.jsdelivr.net/npm/@mediapipe/hands',
  modelType: 'full'
}
const detector = await handPoseDetection.createDetector(model, detectorConfig);
```

**Comment by ziyuan-linn** [comment]
I agree with everything said here! We are no longer using `MediaPipe Handpose` as our underlying model anyways. I can quickly make a PR to change all models to camelCase. However, the change would only take effect after our next release.

I started working on [a guideline addressing this kind of issue](https://github.com/ml5js/ml5-next-gen/pull/73 ) a while ago but I have forgotten about it since. Feel free to take a look and any input is welcome!

**Comment by sproutleaf** [comment]
I'm a big fan of camelCase! All for standardizing all the names to camelCase

**Comment by shiffman** [comment]
We discussed this today in our NYC meeting and decided to go for camelCase! @ziyuan-linn will make the changes!
